#!/bin/sh
echo "Running pre-push hooks..."
cargo fmt -- --check
if [ $? -ne 0 ]; then
  echo "Cargo format check failed. Please run cargo fmt."
  exit 1
fi
cargo clippy --all-targets -- -D warnings
if [ $? -ne 0 ]; then
  echo "Cargo clippy check failed. Please fix warnings/errors."
  exit 1
fi
echo "Pre-push hooks passed."

