[package]
name = "workspace"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0.0"
leptos = "0.7"
reqwest = { version = "0.11", features = ["blocking"] }

playwright = "0.0.20"

tokio = { version = "1", features = ["full"] }

