name: CI
on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Setup Dagger
        uses: dagger/setup-dagger@v3
      
      - name: Initialize Dagger project
        run: |
          cd ci
          go mod init ci
          go get dagger.io/dagger@latest
      
      - name: Run Dagger pipeline
        run: |
          cd ci
          go run main.go
