name: CI
on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Setup Dagger
        uses: dagger/dagger-for-github@v3
      
      - name: Initialize Dagger project
        run: |
          cd ci
          go mod init ci
          go get dagger.io/dagger@latest
      
      - name: Run Dagger pipeline
        run: |
          cd ci
          go run main.go

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Run cargo tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose -- --nocapture

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
