name: CI
on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Dagger
        uses: dagger/setup-dagger@v3
      
      - name: Run checks
        run: |
          dagger run -- cargo fmt --check
          dagger run -- cargo clippy --all-targets --all-features -- -D warnings
          dagger run -- cargo test
