name: AWS CDK Deployment
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  GITHUB_ORG: ${{ github.repository_owner }}
  GITHUB_REPO: ${{ github.event.repository.name }}

defaults:
  run:
    working-directory: infra/
  
env:
  NODE_PATH: ${{ github.workspace }}/node_modules

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: infra/package.json
          cache-dependency-path: infra/package-lock.json

      - name: Install all dependencies
        run: |
          # Install root dependencies
          npm ci
          
          # Install infra dependencies with explicit path resolution
          cd infra
          npm ci
          cd ..
          
          # Verify module resolution
          echo "Root node_modules: $(npm root)"
          echo "Infra node_modules: $(cd infra && npm root)"
          echo "NODE_PATH: $NODE_PATH"

      - name: Test
        run: |
          cd infra
          npx ts-jest config:init
          npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy infrastructure
        run: |
          npx cdk deploy --require-approval never
          echo "Infrastructure deployed successfully"

      - name: Output deployment details
        run: |
          echo "Deployment completed at $(date)"
          echo "GitHub Org: $GITHUB_ORG"
          echo "GitHub Repo: $GITHUB_REPO"
