name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths: [ 'infra/**' ]
  pull_request:
    paths: [ 'infra/**' ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g aws-cdk
      - run: cd infra && npm install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - run: cd infra && npx cdk synth
      - if: github.ref == 'refs/heads/main'
        run: cd infra && npx cdk deploy --require-approval never