name: AWS CDK Deployment
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  GITHUB_ORG: ${{ github.repository_owner }}
  GITHUB_REPO: ${{ github.event.repository.name }}

defaults:
  run:
    working-directory: infra/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: infra/package.json

      - name: Install dependencies
        run: npm ci

      - name: Build and test
        working-directory: infra
        run: |
          npm run build
          npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy infrastructure
        working-directory: infra
        run: |
          npx cdk deploy --require-approval never
          echo "Infrastructure deployed successfully"

      - name: Output deployment details
        run: |
          echo "Deployment completed at $(date)"
          echo "GitHub Org: $GITHUB_ORG"
          echo "GitHub Repo: $GITHUB_REPO"
